# Generated by Django 2.1 on 2019-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_profile_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
